#!/bin/bash
# Generate elastic-agent.yml.env from AWS SSM.
# Usage: generate_env.sh <output_path>
#
# Mirrors cookbooks/lxc-elasticsearch/files/generate_env.sh (AWS_PROFILE +
# AWS_REGION inherited from default.rb sourcing aws-config.json), but only
# fetches the single secret the standalone Elastic Agent needs. Output is a
# bare KEY=VALUE file consumed by systemd's EnvironmentFile=, which does NOT
# perform shell expansion — passwords with metacharacters survive intact.

set -euo pipefail

OUTPUT_FILE="${1:?usage: $0 <output_path>}"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --profile "${AWS_PROFILE}" \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ELASTIC_AGENT_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-agent-password")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by elastic-agent cookbook — do not edit
ELASTIC_AGENT_PASSWORD=${ELASTIC_AGENT_PASSWORD}
EOF

chmod 600 "${OUTPUT_FILE}"
