
[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[env]
LANG = "en_US.UTF-8"
LC_TYPE = "en_US.UTF-8"

[font]
size = 16.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "✠"
key = 36
mods = "Command"

[window]
decorations = "buttonless"
opacity = 0.95

[window.dimensions]
columns = 200
lines = 75

[window.padding]
x = 10
y = 5

[window.position]
x = 0
y = 0

[general]
live_config_reload = true
