#!/bin/bash
# Generate .env for ai-memory Docker Compose from AWS SSM Parameter Store
# Usage: generate_env.sh <output_path>

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${AWS_REGION}" 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

AURORA_ENDPOINT=$(fetch_ssm "/memory/aurora-endpoint")
AURORA_PASSWORD=$(fetch_ssm "/memory/aurora-password")
OPENAI_API_KEY=$(fetch_ssm "/mcp/openai-api-key")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by ai-memory cookbook — do not edit
DATABASE_URL=postgresql://mem0:${AURORA_PASSWORD}@${AURORA_ENDPOINT}:5432/mem0
PG_HOST=${AURORA_ENDPOINT}
PG_PORT=5432
PG_DB=mem0
PG_USER=mem0
PG_PASSWORD=${AURORA_PASSWORD}
OPENAI_API_KEY=${OPENAI_API_KEY}
MEM0_USER=shin1ohno
EOF

chmod 600 "${OUTPUT_FILE}"
