#!/bin/bash
# Generate .env for the local-mcp Docker Compose (MacBook Air).
# Usage: generate_env.local.sh <output_path>
#
# LLM / OpenAI keys come from AWS SSM (same params as the home cognee/ai-memory
# stacks) with an OPERATOR-ENV FALLBACK: if Air lacks SSM access, pre-export
# COGNEE_LLM_API_KEY / OPENAI_API_KEY (etc.) and run this script manually, then
# re-run mitamae (which skips regeneration because .env now exists).
#
# Database endpoints/passwords are LOCAL STATIC NON-SECRETS (loopback-only DB
# inside the Docker Desktop VM). They MUST match the literals in
# cookbooks/local-mcp/files/postgres-init/01-databases.sql.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

# --- local static DB credentials (keep in sync with 01-databases.sql) ---
PG_SUPER_PASSWORD="postgres_local_dev"
COGNEE_DB_PASSWORD="cognee_local_dev"
MEM0_DB_PASSWORD="mem0_local_dev"
# Dummy token: cognee API runs with ENABLE_BACKEND_ACCESS_CONTROL=false.
COGNEE_MCP_API_TOKEN="local-dev"

fetch_ssm() {
  aws ssm get-parameter \
    --name "$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" 2>/dev/null \
    || return 1
}

# SSM first, operator-env fallback second.
LLM_ENDPOINT=$(fetch_ssm "/cognee/llm-endpoint"     || echo "${COGNEE_LLM_ENDPOINT:-https://api.openai.com/v1}")
LLM_API_KEY=$( fetch_ssm "/cognee/llm-api-key"      || echo "${COGNEE_LLM_API_KEY:-${OPENAI_API_KEY:-}}")
LLM_MODEL=$(   fetch_ssm "/cognee/llm-model"        || echo "${COGNEE_LLM_MODEL:-openai/gpt-5-mini}")
EMBEDDING_MODEL=$(fetch_ssm "/cognee/embedding-model" || echo "${COGNEE_EMBEDDING_MODEL:-openai/text-embedding-3-small}")
OPENAI_KEY=$(  fetch_ssm "/mcp/openai-api-key"      || echo "${OPENAI_API_KEY:-${LLM_API_KEY}}")

if [ -z "${LLM_API_KEY}" ]; then
  echo "ERROR: no LLM_API_KEY (SSM /cognee/llm-api-key failed and no COGNEE_LLM_API_KEY/OPENAI_API_KEY in env)." >&2
  echo "       cognify/embeddings will fail. Export a key and re-run." >&2
  exit 1
fi

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by local-mcp cookbook (Air) — do not edit

# --- shared local Postgres (non-secret, loopback-only) ---
PG_SUPER_PASSWORD=${PG_SUPER_PASSWORD}
COGNEE_DB_PASSWORD=${COGNEE_DB_PASSWORD}
COGNEE_MCP_API_TOKEN=${COGNEE_MCP_API_TOKEN}
MEM0_USER=shin1ohno

# --- cognee: LLM + embeddings (OpenAI) ---
LLM_PROVIDER=openai
LLM_MODEL=${LLM_MODEL}
LLM_ENDPOINT=${LLM_ENDPOINT}
LLM_API_KEY=${LLM_API_KEY}
EMBEDDING_PROVIDER=openai
EMBEDDING_MODEL=${EMBEDDING_MODEL}
EMBEDDING_ENDPOINT=${LLM_ENDPOINT}
EMBEDDING_API_KEY=${LLM_API_KEY}
EMBEDDING_DIMENSIONS=1536

# --- cognee: graph (embedded kuzu) + vector (local pgvector) ---
GRAPH_DATABASE_PROVIDER=kuzu
VECTOR_DB_PROVIDER=pgvector
VECTOR_DB_HOST=postgres
VECTOR_DB_PORT=5432
VECTOR_DB_NAME=cognee
VECTOR_DB_USERNAME=cognee
VECTOR_DB_PASSWORD=${COGNEE_DB_PASSWORD}

# --- openmemory: local Postgres + qdrant ---
DATABASE_URL=postgresql://mem0:${MEM0_DB_PASSWORD}@postgres:5432/mem0
PG_HOST=postgres
PG_PORT=5432
PG_DB=mem0
PG_USER=mem0
PG_PASSWORD=${MEM0_DB_PASSWORD}
OPENAI_API_KEY=${OPENAI_KEY}
EOF

chmod 600 "${OUTPUT_FILE}"
