#!/bin/bash
# Generate keeper.env for the memory-keeper worker (mini) from AWS SSM.
# Usage: generate_keeper_env.sh <output_path>
#
# Fetches the ES superuser password (/monitoring/elastic/elastic-password) and
# the Voyage AI key (/memory/voyage-api-key) via the pve-bootstrap-ssm profile
# (both paths are inside its scoped SSM + KMS grant). Writes the exact key set
# from the frozen contract §2c, then chmod 600. AWS_PROFILE / AWS_REGION come
# from the calling cookbook's environment.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
PROFILE_ARG=""
[ -n "${AWS_PROFILE:-}" ] && PROFILE_ARG="--profile ${AWS_PROFILE}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${AWS_REGION}" ${PROFILE_ARG} 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ES_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-password")
VOYAGE_API_KEY=$(fetch_ssm "/memory/voyage-api-key")

umask 077
cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by cookbooks/memory-keeper — do not edit
ES_URL=https://192.168.1.77:9200
ES_USER=elastic
ES_PASSWORD=${ES_PASSWORD}
ES_VERIFY_CERTS=false
VOYAGE_API_KEY=${VOYAGE_API_KEY}
VOYAGE_ENDPOINT=https://api.voyageai.com/v1
EMBEDDING_MODEL=voyage-3-large
EMBEDDING_DIMENSIONS=1024
FACT_INDEX=memory-fact
KNOWLEDGE_INDEX=memory-knowledge
EPISODE_INDEX=memory-episode
STATS_INDEX=memory-stats
ALL_ALIAS=memory-all
CLAUDE_BIN=/Users/shin1ohno/.local/bin/claude
RECONCILE_MODEL=sonnet
CONSOLIDATE_MODEL=opus
RECONCILE_BATCH=10
KEEPER_HOST=mini
HOME=/Users/shin1ohno
EOF

chmod 600 "${OUTPUT_FILE}"
