#!/bin/bash
# Generate .env for the elasticsearch docker-compose stack from AWS SSM.
# Usage: generate_env.sh <output_path> <node_name> <transport_host>
#
# Mirrors cookbooks/lxc-monitoring/files/generate_env.sh: AWS_PROFILE +
# AWS_REGION are passed in by default.rb (sourced from
# cookbooks/ssh-keys/files/aws-config.json) so this script always targets
# the same IAM principal as the require_external_auth gate. NODE_NAME
# and TRANSPORT_HOST are per-LXC; everything else comes from SSM.

set -euo pipefail

OUTPUT_FILE="$1"
NODE_NAME="$2"
TRANSPORT_HOST="$3"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --profile "${AWS_PROFILE}" \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ELASTIC_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-password")
KIBANA_PASSWORD=$(fetch_ssm "/monitoring/elastic/kibana-password")
VECTOR_PASSWORD=$(fetch_ssm "/monitoring/elastic/vector-password")
GRAFANA_PASSWORD=$(fetch_ssm "/monitoring/elastic/grafana-password")
ANALYST_PASSWORD=$(fetch_ssm "/monitoring/elastic/analyst-password")
MONITOR_PASSWORD=$(fetch_ssm "/monitoring/elastic/monitor-password")
ELASTIC_AGENT_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-agent-password")
APM_SERVER_PASSWORD=$(fetch_ssm "/monitoring/elastic/apm-server-password")
ELASTALERT_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastalert-password")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-elasticsearch cookbook — do not edit
NODE_NAME=${NODE_NAME}
TRANSPORT_HOST=${TRANSPORT_HOST}
ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
KIBANA_PASSWORD=${KIBANA_PASSWORD}
VECTOR_PASSWORD=${VECTOR_PASSWORD}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
ANALYST_PASSWORD=${ANALYST_PASSWORD}
MONITOR_PASSWORD=${MONITOR_PASSWORD}
ELASTIC_AGENT_PASSWORD=${ELASTIC_AGENT_PASSWORD}
APM_SERVER_PASSWORD=${APM_SERVER_PASSWORD}
ELASTALERT_PASSWORD=${ELASTALERT_PASSWORD}
EOF

chmod 600 "${OUTPUT_FILE}"
