#!/bin/bash
# Generate .env for cognee Docker Compose from AWS SSM Parameter Store
# Usage: generate_env.sh <output_path>
#
# AWS_PROFILE + AWS_REGION are passed in by the default.rb caller (sourced
# from cookbooks/ssh-keys/files/devices.json) so the script always targets
# the same IAM principal as the require_external_auth gate.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

LLM_ENDPOINT=$(fetch_ssm "/cognee/llm-endpoint")
LLM_API_KEY=$(fetch_ssm "/cognee/llm-api-key")
LLM_MODEL=$(fetch_ssm "/cognee/llm-model" 2>/dev/null || echo "openai/gpt-5-mini")
EMBEDDING_MODEL=$(fetch_ssm "/cognee/embedding-model" 2>/dev/null || echo "openai/text-embedding-3-small")

# OAuth2 proxy + MCP API token. Required by cognee-oauth2-proxy and cognee-mcp.
# Stored in SSM as SecureString. Rotate with `hydra update oauth2-client` for
# OAUTH2_CLIENT_SECRET; OAUTH2_COOKIE_SECRET and COGNEE_MCP_API_TOKEN are
# free-form random strings (regenerate with openssl rand).
OAUTH2_CLIENT_SECRET=$(fetch_ssm "/cognee/oauth2-client-secret")
OAUTH2_COOKIE_SECRET=$(fetch_ssm "/cognee/oauth2-cookie-secret")
COGNEE_MCP_API_TOKEN=$(fetch_ssm "/cognee/mcp-api-token")

# Relational DB on shared RDS Postgres (mem0 instance). Replaces the
# in-container SQLite that suffered byte-0 corruption 2026-05-11.
# /cognee/db-host and /cognee/db-password are managed by home-monitor
# terraform (rds.tf — postgresql_role.cognee + postgresql_database.cognee
# + aws_ssm_parameter.cognee_db_{host,password}).
DB_HOST=$(fetch_ssm "/cognee/db-host")
DB_PASSWORD=$(fetch_ssm "/cognee/db-password")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by cognee cookbook — do not edit
LLM_PROVIDER=openai
LLM_MODEL=${LLM_MODEL}
LLM_ENDPOINT=${LLM_ENDPOINT}
LLM_API_KEY=${LLM_API_KEY}

# Embeddings hit the same OpenAI endpoint — fastembed/onnxruntime require
# AVX2 which the deploy host does not provide, so a remote provider is required.
EMBEDDING_PROVIDER=openai
EMBEDDING_MODEL=${EMBEDDING_MODEL}
EMBEDDING_ENDPOINT=${LLM_ENDPOINT}
EMBEDDING_API_KEY=${LLM_API_KEY}
EMBEDDING_DIMENSIONS=1536

GRAPH_DATABASE_PROVIDER=kuzu
VECTOR_DB_PROVIDER=chromadb

OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
OAUTH2_COOKIE_SECRET=${OAUTH2_COOKIE_SECRET}
COGNEE_MCP_API_TOKEN=${COGNEE_MCP_API_TOKEN}

DB_HOST=${DB_HOST}
DB_PASSWORD=${DB_PASSWORD}

# Vector DB also on shared RDS Postgres (replaces ChromaDB). pgvector
# extension is enabled on the cognee database. Cognee shares the SQLAlchemy
# engine when relational and vector are both Postgres (PGVectorAdapter
# detects this and reuses connection pool).
VECTOR_DB_PROVIDER=pgvector
VECTOR_DB_HOST=${DB_HOST}
VECTOR_DB_PORT=5432
VECTOR_DB_NAME=cognee
VECTOR_DB_USERNAME=cognee
VECTOR_DB_PASSWORD=${DB_PASSWORD}
EOF

chmod 600 "${OUTPUT_FILE}"
