#!/bin/bash
# Generate the docker-compose .env for local-es-memory from AWS SSM.
# Usage: generate_env.sh <output_path>
#
# darwin-only, single secret: VOYAGE_API_KEY (voyage-3-large embeddings). ES runs
# with security disabled (loopback single-node) so no elastic-password is needed
# — unlike the LXC generate_env_v2.sh which also fetches /monitoring/elastic/*.
#
# Profile: `default` (NOT pve-bootstrap-ssm). On this Mac the pve-bootstrap-ssm
# token is stale; the `aws login` `default` identity has ssm:GetParameter on
# /memory/* and matches the existing darwin mcp/codex-cli SSM convention.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-default}"

VOYAGE_API_KEY=$(aws ssm get-parameter \
  --name /memory/voyage-api-key \
  --with-decryption \
  --query "Parameter.Value" \
  --output text \
  --profile "${AWS_PROFILE}" \
  --region "${AWS_REGION}") \
  || { echo "SSM_FETCH_FAILED:/memory/voyage-api-key (profile=${AWS_PROFILE})" >&2; exit 1; }

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by local-es-memory cookbook (generate_env.sh) — do not edit
VOYAGE_API_KEY=${VOYAGE_API_KEY}
EOF

chmod 600 "${OUTPUT_FILE}"
