#!/bin/bash
# Generate .env for the praeco / elastalert-server docker-compose stack
# from AWS SSM. Mirrors cookbooks/lxc-monitoring/files/generate_env.sh.
# Usage: generate_env.sh <output_path>

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --profile "${AWS_PROFILE}" \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ELASTALERT_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastalert-password")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-praeco cookbook — do not edit
ELASTALERT_USERNAME=elastalert_writer
ELASTALERT_PASSWORD=${ELASTALERT_PASSWORD}
EOF

chmod 600 "${OUTPUT_FILE}"
