#!/bin/bash
# Generate .env for es-memory-mcp Docker Compose from AWS SSM Parameter Store.
# Usage: generate_env.sh <output_path>
#
# Pulls the ES superuser password and OpenAI key. ES_URL targets es-0; the
# httpx client follows the node it is given (any cluster member serves the
# whole index). Embedding model/dims mirror the Cognee config so migrated
# vectors stay compatible (text-embedding-3-small, 1536-dim).

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
ES_URL="${ES_URL:-https://192.168.1.77:9200}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${AWS_REGION}" 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ELASTIC_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-password")
# Reuse cognee's OpenAI key at /cognee/llm-api-key: it is in the
# pve-bootstrap-ssm IAM grant (/cognee/* + KMS EncryptionContext) and holds the
# same OpenAI key + models (text-embedding-3-small / gpt-5-mini) this server
# uses. /mcp/openai-api-key is NOT in the fleet grant → AccessDenied at apply.
OPENAI_API_KEY=$(fetch_ssm "/cognee/llm-api-key")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-es-memory cookbook — do not edit
ES_URL=${ES_URL}
ES_USER=elastic
ES_PASSWORD=${ELASTIC_PASSWORD}
ES_VERIFY_CERTS=false
OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_ENDPOINT=https://api.openai.com/v1
EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_DIMENSIONS=1536
LLM_MODEL=gpt-5-mini
MEM0_USER=shin1ohno
EOF

chmod 600 "${OUTPUT_FILE}"
