#!/bin/bash
# Generate memory-v2.env for the memory-mcp v2 server from AWS SSM Parameter
# Store. Usage: generate_env_v2.sh <output_path>
#
# v2 (Voyage embeddings) — contract §2a keys ONLY. Index names come from the
# systemd unit's Environment= lines, NOT this .env. Deliberately drops the v1
# OPENAI_* keys and MEM0_USER: v2 embeds via Voyage (voyage-3-large, 1024-dim)
# and derives identity from provenance, not a static user id.
#
# ES_URL targets es-0 (192.168.1.77); the httpx client follows the node it is
# given (any cluster member serves the whole index).
#
# Session search (docs/design/claude-session-search.md §6.5 / §7.6):
#   SESSION_SCOPE_POLICY  the personal boundary's identity -> host + scopes
#                         table (non-secret JSON). Written single-quoted: the
#                         systemd EnvironmentFile parser strips unprotected
#                         double quotes, which would break the JSON.
#   SESSION_ARCHIVE_*     the S3 archive writer, read from
#                         /es-memory-ct119/session-archive/* with the CT 119-only
#                         profile named by $SESSION_ARCHIVE_PROFILE. The operator
#                         places that profile (bin/bootstrap-lxc-creds
#                         --profile), so it is optional here: when it is unset or
#                         any of the three reads fails, the archive variables are
#                         left out with a WARN; the server then answers
#                         archive:"skipped" while ingest, search and purge work.
# PROXY_SHARED_SECRET is NOT written here: it lives in its own root-only file
# (/opt/es-memory/proxy-secret.env), generated once on the box and read by both
# the server and the proxy unit, so the two can never disagree.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
ES_URL="${ES_URL:-https://192.168.1.77:9200}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${AWS_REGION}" 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ELASTIC_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-password")
# Voyage API key at /memory/voyage-api-key (SecureString, aws/ssm managed key).
# /memory/* is already in the pve-bootstrap-ssm IAM grant (+ per-path KMS
# EncryptionContext) — no IAM change needed.
VOYAGE_API_KEY=$(fetch_ssm "/memory/voyage-api-key")

# First matching rule wins; no match = deny. memory-mirror and the work account
# (sh1@mercari.com, also in the proxy's ALLOWED_SUBS) deliberately get no rule.
SESSION_SCOPE_POLICY='{"rules":[{"match":{"grant":"client_credentials","client_id":"session-search-pro-dev"},"host":"pro-dev","scopes":["sessions:ingest","sessions:read"]},{"match":{"grant":"client_credentials","client_id":"session-search-mini"},"host":"mini","scopes":["sessions:ingest","sessions:read"]},{"match":{"grant":"client_credentials","client_id":"session-search-neo"},"host":"neo","scopes":["sessions:ingest","sessions:read"]},{"match":{"grant":"authorization_code","sub":"shin1ohno@gmail.com"},"host":null,"scopes":["sessions:read","sessions:purge"]}]}'

fetch_archive() {
  aws ssm get-parameter \
    --name "$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --profile "${SESSION_ARCHIVE_PROFILE}" \
    --region "${AWS_REGION}" 2>/dev/null
}

ARCHIVE_LINES=""
if [ -n "${SESSION_ARCHIVE_PROFILE:-}" ] &&
   ARCHIVE_BUCKET=$(fetch_archive "/es-memory-ct119/session-archive/bucket-name") &&
   ARCHIVE_AKID=$(fetch_archive "/es-memory-ct119/session-archive/access-key-id") &&
   ARCHIVE_SECRET=$(fetch_archive "/es-memory-ct119/session-archive/secret-access-key") &&
   [ -n "${ARCHIVE_BUCKET}" ] && [ -n "${ARCHIVE_AKID}" ] && [ -n "${ARCHIVE_SECRET}" ]; then
  ARCHIVE_LINES="SESSION_ARCHIVE_BACKEND=s3
SESSION_ARCHIVE_BUCKET=${ARCHIVE_BUCKET}
SESSION_ARCHIVE_AWS_REGION=${AWS_REGION}
SESSION_ARCHIVE_AWS_ACCESS_KEY_ID=${ARCHIVE_AKID}
SESSION_ARCHIVE_AWS_SECRET_ACCESS_KEY=${ARCHIVE_SECRET}"
else
  echo "WARN: session archive writer unavailable (profile '${SESSION_ARCHIVE_PROFILE:-unset}' or /es-memory-ct119/session-archive/* unreadable) — writing memory-v2.env without SESSION_ARCHIVE_*" >&2
fi

umask 077
cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-es-memory cookbook (generate_env_v2.sh) — do not edit
ES_URL=${ES_URL}
ES_USER=elastic
ES_PASSWORD=${ELASTIC_PASSWORD}
ES_VERIFY_CERTS=false
VOYAGE_API_KEY=${VOYAGE_API_KEY}
VOYAGE_ENDPOINT=https://api.voyageai.com/v1
EMBEDDING_MODEL=voyage-3-large
EMBEDDING_DIMENSIONS=1024
SESSION_SCOPE_POLICY='${SESSION_SCOPE_POLICY}'
EOF
if [ -n "${ARCHIVE_LINES}" ]; then
  printf '%s\n' "${ARCHIVE_LINES}" >> "${OUTPUT_FILE}"
fi

chmod 600 "${OUTPUT_FILE}"
