#!/bin/bash
# Generate memory-v2.env for the memory-mcp v2 server from AWS SSM Parameter
# Store. Usage: generate_env_v2.sh <output_path>
#
# v2 (Voyage embeddings) — contract §2a keys ONLY. Index names come from the
# systemd unit's Environment= lines, NOT this .env. Deliberately drops the v1
# OPENAI_* keys and MEM0_USER: v2 embeds via Voyage (voyage-3-large, 1024-dim)
# and derives identity from provenance, not a static user id.
#
# ES_URL targets es-0 (192.168.1.77); the httpx client follows the node it is
# given (any cluster member serves the whole index).

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
ES_URL="${ES_URL:-https://192.168.1.77:9200}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${AWS_REGION}" 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

ELASTIC_PASSWORD=$(fetch_ssm "/monitoring/elastic/elastic-password")
# Voyage API key at /memory/voyage-api-key (SecureString, aws/ssm managed key).
# /memory/* is already in the pve-bootstrap-ssm IAM grant (+ per-path KMS
# EncryptionContext) — no IAM change needed.
VOYAGE_API_KEY=$(fetch_ssm "/memory/voyage-api-key")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-es-memory cookbook (generate_env_v2.sh) — do not edit
ES_URL=${ES_URL}
ES_USER=elastic
ES_PASSWORD=${ELASTIC_PASSWORD}
ES_VERIFY_CERTS=false
VOYAGE_API_KEY=${VOYAGE_API_KEY}
VOYAGE_ENDPOINT=https://api.voyageai.com/v1
EMBEDDING_MODEL=voyage-3-large
EMBEDDING_DIMENSIONS=1024
EOF

chmod 600 "${OUTPUT_FILE}"
