#!/bin/bash
# Generate .env for the kibana docker-compose stack from AWS SSM.
# Usage: generate_env.sh <output_path>

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --profile "${AWS_PROFILE}" \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

KIBANA_PASSWORD=$(fetch_ssm "/monitoring/elastic/kibana-password")
KIBANA_ENC_SO_KEY=$(fetch_ssm     "/monitoring/elastic/kibana/encryption-key/encrypted-saved-objects")
KIBANA_ENC_REPORT_KEY=$(fetch_ssm "/monitoring/elastic/kibana/encryption-key/reporting")
KIBANA_ENC_SEC_KEY=$(fetch_ssm    "/monitoring/elastic/kibana/encryption-key/security")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-kibana cookbook — do not edit
KIBANA_PASSWORD=${KIBANA_PASSWORD}
KIBANA_ENC_SO_KEY=${KIBANA_ENC_SO_KEY}
KIBANA_ENC_REPORT_KEY=${KIBANA_ENC_REPORT_KEY}
KIBANA_ENC_SEC_KEY=${KIBANA_ENC_SEC_KEY}
EOF

chmod 600 "${OUTPUT_FILE}"
