#!/bin/bash
# Generate .env for Hydra Docker Compose from AWS SSM Parameter Store
# Usage: generate_env.sh <output_path>

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"

fetch_ssm() {
  local param_path="$1"
  aws ssm get-parameter \
    --name "${param_path}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${AWS_REGION}" 2>/dev/null \
    || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

AURORA_ENDPOINT=$(fetch_ssm "/memory/aurora-endpoint")
HYDRA_PASSWORD=$(fetch_ssm "/hydra/aurora-password")
HYDRA_SYSTEM_SECRET=$(fetch_ssm "/hydra/system-secret")
GOOGLE_CLIENT_ID=$(fetch_ssm "/hydra/google-client-id")
GOOGLE_CLIENT_SECRET=$(fetch_ssm "/hydra/google-client-secret")
ALLOWED_EMAILS=$(fetch_ssm "/hydra/allowed-emails")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by hydra cookbook — do not edit
AURORA_ENDPOINT=${AURORA_ENDPOINT}
HYDRA_PASSWORD=${HYDRA_PASSWORD}
HYDRA_SYSTEM_SECRET=${HYDRA_SYSTEM_SECRET}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ALLOWED_EMAILS=${ALLOWED_EMAILS}
EOF

chmod 600 "${OUTPUT_FILE}"
