#!/bin/bash
# Generate .env for monitoring Docker Compose from AWS SSM Parameter Store
# Usage: generate_env.sh <output_path>
#
# Mirrors cookbooks/cognee/files/generate_env.sh with a single secret
# (Grafana admin password). AWS_PROFILE + AWS_REGION are passed in by the
# default.rb caller (sourced from cookbooks/ssh-keys/files/devices.json) so
# the script always targets the same IAM principal as the require_external_auth
# gate — never the host's ambient default profile.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --profile "${AWS_PROFILE}" \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

GRAFANA_ADMIN_PASSWORD=$(fetch_ssm "/monitoring/grafana-admin-password")
PVE_TOKEN_VALUE=$(fetch_ssm "/monitoring/pve-exporter-token")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-monitoring cookbook — do not edit
GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
PVE_TOKEN_VALUE=${PVE_TOKEN_VALUE}
EOF

chmod 600 "${OUTPUT_FILE}"
