#!/bin/bash
# Generate .env for monitoring Docker Compose from AWS SSM Parameter Store
# Usage: generate_env.sh <output_path>
#
# Mirrors cookbooks/cognee/files/generate_env.sh with a single secret
# (Grafana admin password). Region defaults to ap-northeast-1; override
# via AWS_REGION env. Profile inherits the caller's AWS_PROFILE / default.

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

GRAFANA_ADMIN_PASSWORD=$(fetch_ssm "/monitoring/grafana-admin-password")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-monitoring cookbook — do not edit
GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
EOF

chmod 600 "${OUTPUT_FILE}"
