#!/bin/bash
# Generate /etc/apm-server/apm-server-secrets.env from SSM.
# Sourced by systemd EnvironmentFile= (bare KEY=VALUE, no shell expansion)
# so metacharacter-bearing passwords pass through to apm-server literally.
#
# Usage: generate_env.sh <output_path>

set -euo pipefail

OUTPUT_FILE="$1"
AWS_REGION="${AWS_REGION:-ap-northeast-1}"
AWS_PROFILE="${AWS_PROFILE:-pve-bootstrap-ssm}"

fetch_ssm() {
    local param_path="$1"
    aws ssm get-parameter \
        --name "${param_path}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --profile "${AWS_PROFILE}" \
        --region "${AWS_REGION}" 2>/dev/null \
        || { echo "SSM_FETCH_FAILED:${param_path}" >&2; return 1; }
}

APM_SERVER_PASSWORD=$(fetch_ssm "/monitoring/elastic/apm-server-password")

cat > "${OUTPUT_FILE}" <<EOF
# Auto-generated by lxc-apm-server cookbook — do not edit
APM_SERVER_PASSWORD=${APM_SERVER_PASSWORD}
EOF

chmod 600 "${OUTPUT_FILE}"
