# frozen_string_literal: true
#
# macos-hub: Rust binary on the Mac that bridges local audio control
# (Core Audio HAL output switching, CGEvent media keys via MediaRemote
# private API, system volume via osascript) to MQTT. Lives in the
# edge-agent repo at companions/mac/macos-hub/ — NOT published to
# crates.io because it's platform-specific tooling; built from source
# via `cargo install --path`.
#
# Per-host deploy:
#   - cargo install --path …/macos-hub --root ~/.local → ~/.local/bin/macos-hub
#   - $XDG_CONFIG_HOME/macos-hub/macos-hub.toml          (per-host edge_id)
#   - $XDG_STATE_HOME/macos-hub/                         (stdout/stderr logs)
#   - ~/Applications/MacosHub.app                        (.app bundle wrapper
#     so macOS Local Network Privacy can key its grant to a stable
#     CFBundleIdentifier — macos-hub reaches out to mosquitto on LAN.
#     Without the bundle, launchd-launched TCP connects get silently
#     dropped / prompted repeatedly).
#   - ~/Library/LaunchAgents/com.shin1ohno.macos-hub.plist  (Aqua-only unit)
#
# First run requires interactive approval of the Local Network dialog:
#   open ~/Applications/MacosHub.app         # dialog appears, click Allow
#   pkill -f MacosHub.app                    # cleanup
#   launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/com.shin1ohno.macos-hub.plist
# The bundle-ID-keyed grant survives future binary replacements via this cookbook.
#
# Hosts that aren't in HOSTNAME_TO_EDGE_ID are skipped — same pattern as edge-agent.

return unless node[:platform] == "darwin"

HOSTNAME_TO_EDGE_ID = {
  "xmhtm6qvqx" => "air", # MacBook Air
}.freeze

# MQTT broker host for all Macs. Pro.home.local is the Linux server on
# the LAN that runs mosquitto + weave-server + edge-agent.
MQTT_HOST = "pro.home.local"
MQTT_PORT = 1883

current_host = run_command("hostname -s").stdout.strip.downcase
edge_id = HOSTNAME_TO_EDGE_ID[current_host]

if edge_id.nil?
  MItamae.logger.info("macos-hub: hostname '#{current_host}' not in HOSTNAME_TO_EDGE_ID, skipping")
  return
end

user = node[:setup][:user]
home = node[:setup][:home]
repo_path = "#{home}/ManagedProjects/edge-agent"
crate_path = "#{repo_path}/companions/mac/macos-hub"
bin_dir = "#{home}/.local/bin"
bin_path = "#{bin_dir}/macos-hub"

directory bin_dir do
  owner user
  mode "755"
end

# Build + install macos-hub from the local edge-agent repo.
# `cargo install --path --force` always rebuilds; skip via mtime check when
# the existing binary is newer than every source file under the crate.
# The check covers src/ + Cargo.toml + Cargo.lock (the files that actually
# change binary output); target/ is intentionally excluded.
execute "cargo install macos-hub from #{crate_path}" do
  command "#{home}/.cargo/bin/cargo install --path #{crate_path} --root #{home}/.local --locked --force"
  user user
  cwd home
  only_if "test -d #{crate_path}/src"
  not_if "test -x #{bin_path} && " \
         "! find #{crate_path}/src #{crate_path}/Cargo.toml #{crate_path}/Cargo.lock -newer #{bin_path} 2>/dev/null | grep -q ."
end

directory "#{home}/.config/macos-hub" do
  owner user
  mode "755"
end

# Per-host TOML config. `not_if` skips when the file already exists so the
# user can edit it without the cookbook overwriting — mirrors edge-agent's
# config-handling convention.
file "#{home}/.config/macos-hub/macos-hub.toml" do
  owner user
  mode "644"
  content <<~TOML
    # macos-hub config for #{current_host} (#{edge_id})
    # Generated by cookbooks/macos-hub/default.rb — safe to hand-edit.

    [mqtt]
    host = "#{MQTT_HOST}"
    port = #{MQTT_PORT}
    client_id = "macos-hub-#{edge_id}"

    [macos]
    edge_id = "#{edge_id}"
    periodic_publish_interval_secs = 5
  TOML
  not_if "test -f #{home}/.config/macos-hub/macos-hub.toml"
end

directory "#{home}/.local/state/macos-hub" do
  owner user
  mode "755"
end

# .app bundle wrapper so macOS Local Network Privacy attaches its grant to
# a stable CFBundleIdentifier. macos-hub reaches out to mosquitto on the
# LAN; without the bundle, launchd-initiated TCP connects hit the LNP
# permission system and fail unpredictably.

app_bundle = "#{home}/Applications/MacosHub.app"
bundle_exec = "#{app_bundle}/Contents/MacOS/macos-hub"
bundle_info = "#{app_bundle}/Contents/Info.plist"
launchd_plist = "#{home}/Library/LaunchAgents/com.shin1ohno.macos-hub.plist"

directory "#{home}/Applications" do
  owner user
  mode "755"
end

directory "#{app_bundle}/Contents/MacOS" do
  owner user
  mode "755"
end

file bundle_info do
  owner user
  mode "644"
  content <<~PLIST
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>CFBundleIdentifier</key>
        <string>com.shin1ohno.macos-hub</string>
        <key>CFBundleName</key>
        <string>MacosHub</string>
        <key>CFBundleExecutable</key>
        <string>macos-hub</string>
        <key>CFBundleVersion</key>
        <string>0.1.0</string>
        <key>CFBundleShortVersionString</key>
        <string>0.1.0</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>LSUIElement</key>
        <true/>
        <key>NSLocalNetworkUsageDescription</key>
        <string>Connects to the mosquitto MQTT broker on the local network to receive audio-control commands from edge-agents.</string>
    </dict>
    </plist>
  PLIST
end

directory "#{home}/Library/LaunchAgents" do
  owner user
  mode "755"
end

file launchd_plist do
  owner user
  mode "644"
  content <<~PLIST
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.shin1ohno.macos-hub</string>
        <key>ProgramArguments</key>
        <array>
            <string>#{bundle_exec}</string>
            <string>#{home}/.config/macos-hub/macos-hub.toml</string>
        </array>
        <key>EnvironmentVariables</key>
        <dict>
            <key>RUST_LOG</key>
            <string>info</string>
            <key>PATH</key>
            <string>#{home}/.cargo/bin:/usr/local/bin:/usr/bin:/bin</string>
        </dict>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <dict>
            <key>SuccessfulExit</key>
            <false/>
            <key>NetworkState</key>
            <true/>
        </dict>
        <key>ThrottleInterval</key>
        <integer>30</integer>
        <key>StandardOutPath</key>
        <string>#{home}/.local/state/macos-hub/#{edge_id}.log</string>
        <key>StandardErrorPath</key>
        <string>#{home}/.local/state/macos-hub/#{edge_id}.err.log</string>
        <key>WorkingDirectory</key>
        <string>#{home}</string>
        <key>LimitLoadToSessionType</key>
        <string>Aqua</string>
    </dict>
    </plist>
  PLIST
end

# Sync binary + ad-hoc sign + reload launchd whenever bin_path is newer than
# the bundled copy (same pattern as edge-agent cookbook). `-nt` is true when
# the right-hand side is *not newer*, so `not_if` fires when the bundle is
# already up to date. The unload tolerates "not currently loaded" (first run
# before interactive bootstrap) via `2>/dev/null || true`; load is only
# reached if cp + codesign succeeded so a failing codesign leaves the old
# binary + launchd state intact. Declared AFTER the launchd_plist file so
# first-run ordering works (the plist must exist before launchctl load).
execute "sync MacosHub.app binary, codesign, and reload launchd" do
  command "cp -f #{bin_path} #{bundle_exec} && " \
          "codesign --force --deep --sign - #{app_bundle} && " \
          "{ launchctl unload #{launchd_plist} 2>/dev/null || true; } && " \
          "launchctl load #{launchd_plist}"
  user user
  only_if "test -x #{bin_path}"
  not_if "test -x #{bundle_exec} && ! [ #{bin_path} -nt #{bundle_exec} ]"
end
