name: Test Setup Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_full_install:
        description: 'Run full installation test (not just dry-run)'
        required: false
        default: false
        type: boolean

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    
    - name: Check bin scripts are executable
      run: |
        test -x bin/setup
        test -x bin/cookbook
    
    - name: Download mitamae binary
      run: |
        mkdir -p $HOME/tmp
        ./bin/setup
      
    - name: Verify mitamae installation
      run: |
        test -x bin/mitamae
        ./bin/mitamae version
    
    - name: Test darwin.rb in dry-run mode
      run: |
        # Create writable temp directory  
        sudo chmod 777 /tmp
        ./bin/mitamae local darwin.rb --dry-run
        
    - name: Test partial installation (core tools only)
      if: ${{ github.event.inputs.run_full_install == 'true' }}
      run: |
        sudo chmod 777 /tmp
        cat > test_core_install.rb << 'EOF'
        include_recipe "cookbooks/functions/default.rb"
        include_cookbook "homebrew"
        include_cookbook "git"
        include_cookbook "zsh"
        EOF
        ./bin/mitamae local test_core_install.rb
      
    - name: Verify setup structure
      run: |
        echo "Checking project structure..."
        ls -la roles/
        ls -la cookbooks/ | head -10
        echo "Main entry points exist:"
        test -f darwin.rb && echo "✓ darwin.rb found"
        test -f linux.rb && echo "✓ linux.rb found"

  test-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y ruby curl sudo git build-essential
        # Create runner user for consistency with GitHub Actions
        useradd -m -s /bin/bash runner || true
    
    - name: Check bin scripts are executable
      run: |
        test -x bin/setup
        test -x bin/cookbook
    
    - name: Download mitamae binary
      run: ./bin/setup
      
    - name: Verify mitamae installation
      run: |
        test -x bin/mitamae
        ./bin/mitamae version
    
    - name: Test linux.rb in dry-run mode
      run: |
        export USER=runner
        ./bin/mitamae local linux.rb --dry-run
        
    - name: Test partial installation (core tools only)
      if: ${{ github.event.inputs.run_full_install == 'true' }}
      run: |
        export USER=runner
        cat > test_core_install.rb << 'EOF'
        include_recipe "cookbooks/functions/default.rb"
        include_cookbook "git"
        include_cookbook "zsh"
        include_cookbook "tree"
        EOF
        ./bin/mitamae local test_core_install.rb
        
    - name: Verify core installations
      if: ${{ github.event.inputs.run_full_install == 'true' }}
      run: |
        which git && git --version || echo "git not found"
        which zsh && zsh --version || echo "zsh not found"
        which tree && tree --version || echo "tree not found"
      
    - name: Verify setup structure
      run: |
        echo "Checking project structure..."
        ls -la roles/
        ls -la cookbooks/ | head -10
        echo "Main entry points exist:"
        test -f darwin.rb && echo "✓ darwin.rb found" 
        test -f linux.rb && echo "✓ linux.rb found"

  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    
    - name: Check Ruby syntax
      run: |
        echo "Checking Ruby syntax for all .rb files..."
        find . -name "*.rb" -exec ruby -c {} \;
        
    - name: Check for common issues
      run: |
        # Check for syntax errors in main files
        echo "Checking main entry points..."
        ruby -c darwin.rb
        ruby -c linux.rb
        
        # Check for required files
        test -f bin/setup
        test -f bin/cookbook
        test -f bin/mitamae || echo "mitamae binary will be downloaded by setup"
        
        # Check role files exist
        test -d roles/
        test -f roles/core/default.rb
        test -f roles/programming/default.rb
        test -f roles/llm/default.rb
        
        # Check functions helper exists
        test -f cookbooks/functions/default.rb
        
    - name: Validate JSON files
      run: |
        # Check if any JSON files exist and validate them
        if find . -name "*.json" -type f | head -1 | grep -q .; then
          echo "Validating JSON files..."
          find . -name "*.json" -exec python3 -m json.tool {} \; > /dev/null
        else
          echo "No JSON files found to validate"
        fi

  error-simulation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    
    - name: Download mitamae binary
      run: |
        mkdir -p $HOME/tmp
        ./bin/setup
      
    - name: Test basic mitamae functionality
      run: |
        sudo chmod 777 /tmp
        echo "Testing basic mitamae dry-run without recipes..."
        echo '' > empty_test.rb
        ./bin/mitamae local empty_test.rb --dry-run
        
    - name: Check mitamae version compatibility
      run: |
        ./bin/mitamae version
        echo "Mitamae version check completed"